name: Main
on: push
jobs:
  test:
    name: Run code linters and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
	  - name: Install libvirt
        run: sudo apt-get install libvirt-dev
      - name: Run 'make test'
        run: make test
