name: Main
on: push
permissions:
  contents: write
jobs:
  test:
    name: Test and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install libvirt
        run: sudo apt-get install libvirt-dev
      - name: Install dependencies
        run: make setup
      - name: Export GOBIN
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run tests
        run: make test
      - name: Build
        run: make build
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/') # Only release for tagged commits.
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
