name: Main
on: push
jobs:
  test:
    name: Test and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install libvirt
        run: sudo apt-get install libvirt-dev
      - name: Install dependencies
        run: make setup
      - name: Export GOPATH
        run: export PATH="$PATH:$(go env GOPATH)/bin" # Currently the path needs to be set manually.
      - name: Run tests
        run: make test
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/') # Only release for tagged commits.
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
